Added Merge Queue integration to the workflow. Also added webhook to the workflow.
eol-uchile/edx-uabierta pull request #89
Opened 2024-05-23 21:07 UTC by matiasua

2024-05-23 22:31 UTC, fsologureng requested changes

2024-05-23 22:31 UTC, fsologureng commented on .github/workflows/docker.yml
>            docker push ghcr.io/eol-uchile/edx-uabierta:${GITHUB_SHA}
Sacaste el tag `${GITHUB_SHA}` del build así que esto te va a fallar porque no estará construída localmente la imagen "pusheada" aquí.
De acuerdo a lo que hablamos el otro día, para platform, sugiero dejarlo acá tb. Mal no nos va a hacer.

2024-05-23 22:31 UTC, fsologureng commented on .github/workflows/docker.yml
>            docker push ghcr.io/eol-uchile/edx-uabierta:s3-static-${GITHUB_SHA}
Ídem anterior.

2024-05-24 13:42 UTC, matiasua commented on .github/workflows/docker.yml
>            docker push ghcr.io/eol-uchile/edx-uabierta:s3-static-${GITHUB_SHA}
done

2024-05-24 13:42 UTC, matiasua commented on .github/workflows/docker.yml
>            docker push ghcr.io/eol-uchile/edx-uabierta:${GITHUB_SHA}
done;

2024-05-24 13:58 UTC, fsologureng approved these changes

2024-05-24 14:17 UTC, merged